NewsPortal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from NewsPortal import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from NewsPortal import settings
from .views import *

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='news'),
    path('add-rating/', AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>', NewsDetail.as_view(), name='news_detail'),
    path('<slug:slug>/edit', NewsUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', NewsDelete.as_view(), name='delete'),
    path('search/', cache_page(60)(NewsSearch.as_view()), name='search'),
    path('add/', NewsCreate.as_view(), name='create'),
    path('upgrade/', upgrade_to_author, name='upgrade'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/include/footer.html
{#<footer class="editContent">#}
{#    <div class="container">#}
{#        <div class="row footer-top">#}
{#            <div class="col-lg-4 footer-grid_section_w3layouts">#}
{#                <h2 class="logo-2 mb-lg-4 mb-3">#}
{#                    <a href="{% url 'news:news' %}" class="editContent">#}
{#                                <span class="fa" aria-hidden="true">#}
{#                                    News Portal#}
{#                                </span>#}
{#                    </a>#}
{#                </h2>#}

{#                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>#}
{#                <ul class="w3layouts_social_list media-soc list-unstyled">#}
{#                    <li>#}
{#                        <a href="#" class="w3pvt_facebook editContent">#}
{#                            <span class="fa fa-facebook-f"></span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#" class="w3pvt_twitter editContent">#}
{#                            <span class="fa fa-twitter"></span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#" class="w3pvt_dribble editContent">#}
{#                            <span class="fa fa-dribbble"></span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#" class="w3pvt_google editContent">#}
{#                            <span class="fa fa-google-plus"></span>#}
{#                        </a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col-lg-8 footer-left">#}
{#                <div class="w3layouts-news-letter">#}
{#                </div>#}
{#                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">#}
{#                    <div class="col-md-4 footer-grid_section_w3layouts">#}
{#                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">#}
{#                            Разделы</h3>#}
{#                        <ul class="list-unstyled w3layouts-icons">#}
{#                            <li>#}
{#                                <a href="{% url 'news:news' %}" class="editContent">Главная</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="about.html" class="editContent">Категории</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="contact.html" class="editContent">Контакты</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="col-md-4 footer-grid_section_w3layouts">#}
                        <!-- social icons -->
{#                        <div class="agileinfo_social_icons">#}
{#                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">#}
{#                                Pages</h3>#}
{#                            <ul class="list-unstyled w3layouts-icons">#}
{##}
{#                                <li>#}
{#                                    <a href="#" class="editContent">About Us</a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#" class="editContent">About Us</a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#" class="editContent">About Us</a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#" class="editContent">About Us</a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#" class="editContent">About Us</a>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </div>#}
                        <!-- social icons -->
{#                    </div>#}
{#                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">#}
{#                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">#}
{#                            Contact Info</h3>#}
{#                        <div class="contact-info">#}
{#                            <div class="footer-address-inf my-4">#}
{#                                <h4 class="ad-info mb-2 editContent">Email </h4>#}
{#                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a>#}
{#                                </p>#}
{#                            </div>#}
{#                            <div class="footer-address-inf">#}
{#                                <h4 class="ad-info mb-2 editContent">Location</h4>#}
{#                                <p class="editContent">New York City</p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</footer>#}
<!-- //footer -->
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2021 - 2022 NewsPortal. All rights reserved
            </p>
            <!-- move top icon -->
            <a href="#home" class="move-top text-right col-md-2"><span
                    class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
            <!-- //move top icon -->
        </div>
    </div>
</div>

templates/include/pagination.html
  <nav aria-label="Page navigation">
{#        <ul class="pagination pagination-sm justify-content-center">#}
            <ul class="pagination">
            <!-- Проверяем что поддерживается постраничный вывод -->
            {% if is_paginated %}

                <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
                {% if page_obj.has_previous %}
                    <li class="pagination__item"><a href="?page=1" class="pagination__link">First</a></li>
                    <li class="pagination__item"><a href="?page={{ page_obj.previous_page_number }}" class="pagination__link">&laquo;</a></li>
                {% endif %}

                <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="pagination__item active" aria-current="page"><a class="pagination__link">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                        <li class="pagination__item"><a href="?page={{ num }}" class="pagination__link">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
                {% if page_obj.has_next %}
                    <li class="pagination__item"><a href="?page={{ page_obj.next_page_number }}" class="pagination__link">&raquo;</a></li>
                    <li class="pagination__item"><a href="?page={{ page_obj.paginator.num_pages}}" class="pagination__link">Last</a></li>
                {% endif %}

            {% endif %}
        </ul>
    </nav>