NewsPortal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from NewsPortal import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from NewsPortal import settings
from .views import *

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='news'),
    path('add-rating/', AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>', NewsDetail.as_view(), name='news_detail'),
    path('<slug:slug>/edit', NewsUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', NewsDelete.as_view(), name='delete'),
    path('search/', cache_page(60)(NewsSearch.as_view()), name='search'),
    path('add/', NewsCreate.as_view(), name='create'),
    path('upgrade/', upgrade_to_author, name='upgrade'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from pytils.translit import slugify


class Author(models.Model):
    author_name = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Автор')
    author_rating = models.DecimalField(decimal_places=2, max_digits=5, default=0.00)

    def update_rating(self):
        post_rate = self.post_set.aggregate(Sum('post_rating'))
        p_rat = 0
        p_rat += post_rate.get('post_rating__sum')

        comment_rate = self.author_name.comment_set.aggregate(comment_rating=Sum('comment_rating'))
        c_rat = 0
        c_rat += comment_rate.get('comment_rating')

        comment_post_rate = self.post_set.aggregate(comment_rating=Sum('comment__comment_rating'))
        cp_rat = 0
        cp_rat += comment_post_rate.get('comment_rating')

        self.author_rating = p_rat * 3 + c_rat + cp_rat
        self.save()

    def __str__(self):
        return f"{self.author_name}\n" \
               f"(rating:{self.author_rating})"

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Category(models.Model):
    category_name = models.CharField(max_length=255, unique=True, verbose_name='Категория')
    subscribers = models.ManyToManyField(User, through='UserCategorySub')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f"{self.category_name}"

    def get_absolute_url(self):
        return reverse('news:news')


class UserCategorySub(models.Model):
    """M2M table"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} = {self.category}"


class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'
    CHOICE = [
        (ARTICLE, 'article'),
        (NEWS, 'news'),
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    article_or_news = models.CharField(max_length=10,
                                       choices=CHOICE,
                                       default=NEWS)
    date_creation = models.DateField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory', verbose_name='Категория')
    post_title = models.CharField(max_length=128, null=True, verbose_name='Заголовок')
    post_text = models.TextField(verbose_name='Текст статьи')
    # post_rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    post_rating = models.SmallIntegerField("Рейтинг", default=0)
    image = models.ImageField('Картинка', upload_to='news/%Y/%m/%d', null=True, blank=True)
    url = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    # Переопределяем save для кэширования и slug
    def save(self, *args, **kwargs):
        if not self.url:
            self.url = slugify(self.post_title)  # import slugify from pytils.translit для работы с кириллицей
        super(Post, self).save(*args, **kwargs)
        cache.delete(self.pk)

    def get_absolute_url(self):
        return reverse('news:news_detail', kwargs={'slug': self.url})

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return f"{self.post_text[:125]}..."

    def __str__(self):
        return f"{self.author}\n" \
               f"{self.post_rating}\n" \
               f"{self.post_title}\n" \
               f"{self.preview()}\n"

    def get_comment(self):
        return self.comment_set.filter(parent__isnull=True)


class RatingStar(models.Model):
    """Звезды рейтинга"""
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ['-value']


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='Звезда')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Статья')

    def __str__(self):
        return f'{self.star} - {self.post}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class PostCategory(models.Model):
    """M2M table"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=555)
    date_creation = models.DateTimeField(auto_now_add=True)
    comment_rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    email = models.EmailField(verbose_name='Email', blank=True, null=True)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()

    def __str__(self):
        return f"{self.post}\n" \
               f"{self.user}\n" \
               f"{self.text}\n" \
               f"{self.date_creation}\n" \
               f"{self.comment_rating}"

news/forms.py
from allauth.account.forms import SignupForm
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.contrib.auth.models import Group
from django.forms import ModelForm, Textarea, ModelMultipleChoiceField, TextInput, CheckboxSelectMultiple, ImageField
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Post, Category, Comment, Rating, RatingStar


class PostForm(ModelForm):
    """Форма добавления статьи на сайт"""
    # category = ModelMultipleChoiceField(queryset=Category.objects.all(), label='Категория', to_field_name='category_name')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['author'].empty_label = "Автор не выбран"

    class Meta:
        model = Post
        fields = ['post_title', 'post_text', 'category', 'image']
        widgets = {
            'post_title': TextInput(attrs={'class': 'form-input'}),
            'post_text': Textarea(attrs={'cols': 60, 'rows': 10, 'class': 'form-input'}),
            'category': CheckboxSelectMultiple(),
        }


class PostAdminForm(forms.ModelForm):
    """Форма добавления статьи в админке"""
    post_text_ru = forms.CharField(label='Текст[RU]', widget=CKEditorUploadingWidget())
    post_text_en = forms.CharField(label='Текст[EN]', widget=CKEditorUploadingWidget())

    class Meta:
        model = Post
        fields = '__all__'


class CommonSignupForm(SignupForm):
    """Автоматическое добавление зарегистрированного пользователя в общую группу"""
    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user


class CommentForm(forms.ModelForm):
    """Форма комментариев"""
    captcha = ReCaptchaField()

    class Meta:
        model = Comment
        fields = ["text", 'captcha']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control border'}),
        }


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None)

    class Meta:
        model = Rating
        fields = ('star',)


# Если регистрируется через Гугл # TODO make self adding to "common" group through Google
# class LocalSignupForm(forms.Form):
#     pass
#
#     def signup(self, request, user):
#         group = Group.objects.get(name="common")
#         user.groups.add(group)
#         user.save()

news/views.py
import logging
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.cache import cache
from django.core.mail import send_mail, EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .tasks import notify_subscribers, sendNewPost, send_mail_to_subs
from NewsPortal.settings import DEFAULT_FROM_EMAIL
from .filters import PostFilter
from .forms import PostForm, CommentForm, RatingForm
from .models import Post, UserCategorySub, Category, Author, Rating, RatingStar

logger = logging.getLogger(__name__)


# class IsNotAuthor:
#     """Проверяем является ли пользователь автором"""
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
#         context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
#         context['star_form'] = RatingForm()
#         return context


class NewsList(ListView):
    model = Post
    template_name = 'news/news.html'
    context_object_name = 'news'
    ordering = ['-id']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(NewsList, self).get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class NewsDetail(DetailView):
    model = Post
    template_name = 'news/detail_news.html'
    context_object_name = 'detail_news'
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        context['star_form'] = RatingForm()
        context['set_rating'] = Rating.objects.filter(ip=self.request.META.get('REMOTE_ADDR')).exists()
        context['rating'] = Rating.objects.filter(ip=self.request.META.get('REMOTE_ADDR', None))
        if self.request.user.is_authenticated:
            context['author'] = Author.objects.filter(author_name=self.request.user).filter(post__url=self.kwargs['slug'])
        context['form'] = CommentForm()
        return context

    def get_object(self, *args, **kwargs):
        """Берем из кэша"""
        obj = super().get_object(*args, **kwargs)
        cache_obj = cache.get_or_set(self.kwargs["slug"], obj)
        return cache_obj


class NewsSearch(LoginRequiredMixin, ListView):
    """Страница поиска с фильтрами"""
    model = Post
    template_name = 'news/search.html'
    context_object_name = 'news'
    ordering = ['-id']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(NewsSearch, self).get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class NewsCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Добавить статью"""
    template_name = 'news/create_news.html'
    form_class = PostForm
    permission_required = ('news.add_post',)
    slug_field = 'url'

    def form_valid(self, form):
        post = form.save(commit=False)
        try:
            author = Author.objects.get(author_name=self.request.user)
        except Author.DoesNotExist:
            author = Author.objects.create(author_name=self.request.user)
        post.author = author
        post.save()
        # notify_subscribers.apply_async([post.pk], countdown=5)  # После создания отправляем подписчикам письмо через Celery
        notify_subscribers.delay(post.pk)  # После создания отправляем подписчикам письмо через Celery
        return redirect(post.get_absolute_url())


class NewsUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'news/create_news.html'
    form_class = PostForm
    permission_required = ('news.change_post',)

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return Post.objects.get(url=slug)


class NewsDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'news/delete_news.html'
    queryset = Post.objects.all()
    success_url = '/news/'
    permission_required = ('news.delete_post',)
    slug_field = 'url'


class SubscribeView(View):
    """Подписка на рассылку по категориям"""

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        cat_sub = Category.objects.filter(subscribers__email=self.request.user.email).distinct()  # Берем все текущие подписки пользователя
        return render(request, 'news/subscribe.html', context={'categories': categories, 'cat_sub': cat_sub})

    def post(self, request, *args, **kwargs):
        category_name = request.POST.getlist('category_name')
        UserCategorySub.objects.filter(user=request.user).delete()  # Удаляем все подписки этого пользователя из БД

        # Записываем подписки пользователя в БД
        for cat in category_name:
            category = Category.objects.get(category_name=cat)
            subscriber = UserCategorySub(
                user=request.user,
                category=category,
            )
            subscriber.save()

        # send_mail(
        #     subject=f"Спасибо за подписку на NewsPortal",
        #     message=f"Уважаемый {self.request.user.username}, Вы подписались на категории {subscriber.category}",
        #     from_email=DEFAULT_FROM_EMAIL,
        #     recipient_list=[request.user.email]
        # )
        return redirect('news:news')


@login_required
def upgrade_to_author(request):
    """Добавление в группу Authors"""

    user = request.user
    author_group = Group.objects.get(name='authors')
    common_group = Group.objects.get(name='common')  # Если логинится через Гугл
    if not request.user.groups.filter(name='authors').exists():
        author_group.user_set.add(user)
        common_group.user_set.add(user)  # Если логинится через Гугл
    return redirect('news:news')


class AddComment(View):
    """Комментарий"""
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(id=pk)
        user = request.user
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.post = post
            form.user = user
            form.save()
        return redirect(post.get_absolute_url())


class AddStarRating(View):
    """Добавление рейтинга статье"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                post_id=int(request.POST.get("post")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

templates/news/create_news.html
{% extends 'main.html' %}

{% block title %} News Create {% endblock title %}

{% block content %}
    <h2>Добавить статью</h2>
    <hr>
    <div style="margin-left: 30%">
    <form method="post" class="form-input" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Добавить" class="btn btn-success btn-sm">
    </form>
    </div>
{% endblock content %}

templates/news/delete_news.html
{% extends 'main.html' %}

{% block title %} News Delete {% endblock title %}

{% block content %}
    <h2>Удалить пост?</h2>
    <hr>
    <h3>{{ post.post_title }}</h3>
    <p>{{ post.post_text|truncatechars:100 }}</p>

    <form method="post">
        {% csrf_token %}
        <div style="text-align: center"><input type="submit" value="Удалить" class="btn btn-danger"></div>
    </form>

{% endblock content %}

templates/news/detail_news.html
{% extends 'main.html' %}
{% load my_filters %}
{% load static %}

{% block title %}
    {{ detail_news.post_title|censor }}
{% endblock title %}

{% block content %}
    <h2>{{ detail_news.post_title|censor|safe }}</h2>
    <div class="small text-muted"><p>{{ detail_news.date_creation|date:'d M Y' }}</p></div>
    <hr>
    <table>
        <tr>
            <td>
                {% if detail_news.image %}
                    <img src="{{ detail_news.image.url }}" alt="img" class="img-detail">
                {% endif %}
                {{ detail_news.post_text|linebreaks|censor|safe }}
            </td>
        </tr>
    </table>
    {#    ******************************************************************************************    #}
    {#    Рейтинг#}
{##}
{#    <form action="{% url 'news:add_rating' %}" method="post" name="rating">#}
{#        <b>Рейтинг:</b>#}
{#        {% csrf_token %}#}
{#        <input type="hidden" value="{{ detail_news.id }}" name="post">#}
{#        <span class="rating">#}
{##}
{#            {% for k, v in star_form.fields.star.choices %}#}
{##}
{#                {% if set_rating %}#}
{#                    <input type="radio" name="star" id="rating{{ v }}" value="{{ k }}" checked>#}
{#                    <label for="rating{{ v }}">{{ k }}</label>#}
{#                {% else %}#}
{#                    <input type="radio" name="star" id="rating{{ v }}" value="{{ k }}">#}
{#                    <label for="rating{{ v }}">{{ k }}</label>#}
{#                {% endif %}#}
{#            {% endfor %}#}
{##}
{#        </span>#}
{#        <span class="editContent">{{ rating.values.get.star_id }}</span>#}
{#    </form>#}

    {#    ******************************************************************************************    #}
    <p>
    {% if user.is_authenticated %}
        {% if author %}
            <p><a href="{% url 'news:update' detail_news.url %}"><u>Редактировать</u></a></p>
            <p><a href="{% url 'news:delete' detail_news.url %}"><u>Удалить</u></a></p>
        {% endif %}

    </p>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить
                    отзыв</h3>
                <form action="{% url 'news:add_comment' detail_news.pk %}" method="post" class="mt-4" id="formComment">
                    {% csrf_token %}
                    <input type="hidden" name="parent" id="contactparent" value="">
                    <div class="form-group editContent">
                        <label for="contactcomment" class="editContent">
                            Ваш комментарий *
                        </label>
{#                        <textarea class="form-control border" rows="5" name="text"#}
{#                                  id="contactcomment" required=""></textarea>#}
                        {{ form.text }}
                    </div>
                    {{ form.captcha }}
{#                    <div class="d-sm-flex">#}
                        {#                            <div class="col-sm-6 form-group p-0 editContent">#}
                        {#                                <label for="contactusername" class="editContent">#}
                        {#                                    Имя *#}
                        {#                                </label>#}
                        {#                                <input type="text" class="form-control border" name="user"#}
                        {#                                       id="contactusername" required="">#}
                        {#                            </div>#}
                        {#                            <div class="col-sm-6 form-group ml-sm-3 editContent">#}
                        {#                                <label for="contactemail" class="editContent">#}
                        {#                                    Email *#}
                        {#                                </label>#}
                        {#                                <input type="email" class="form-control border" name="email"#}
                        {#                                       id="contactemail" required="">#}
                        {#                            </div>#}
{#                    </div>#}
                    <button type="submit"
                            class="mt-3 btn btn-outline-success btn-sm py-3">
                        Отправить
                    </button>
                </form>
            </div>
            <!--  //contact form grid ends here -->
        </div>
    </div>
    {% endif %}
    <br>
    <div class="small text-muted">Всего комментариев: {{ detail_news.comment_set.count }}</div>
    {% for comment in detail_news.get_comment %}
        <div class="media py-5">
            <img src="{% static 'images/cool-monkey.jpg' %}" class="img-fluid" alt="image">
            <div class="media-body mt-4">
                <h5 class="mt-0 editContent">
                    {{ comment.user }}
                </h5>
                <p class="mt-2 editContent">
                    {{ comment.text }}
                </p>
            {% if user.is_authenticated %}
                <a href="#formComment" onclick="addComment('{{ comment.user }}', '{{ comment.id }}')">Ответить</a>
            {% endif %}
                {% for com in comment.comment_set.all %}
                    <div class="col px-md-5 mt-5">
                        <a class="pr-3" href="#">
                            <img src="{% static 'images/cool-monkey.jpg' %}" class="img-fluid " alt="image">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ com.user }}</h5>
                            <p class="mt-2 editContent">{{ com.text }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <script>
        function addComment(user, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById('contactcomment').innerText = `${user},`
        }
    </script>
{% endblock content %}

templates/news/news.html
{% extends 'main.html' %}
{% load my_filters %}
{% load i18n %}
{% load static %}

{% block title %} News {% endblock title %}

{% block content %}
    <h2>{% trans "Последние публикации" %}</h2>
    <hr>
    {% for new in news %}
        <h5><a href="{% url 'news:news_detail' new.url %}"><strong>{{ new.post_title|censor|safe }}</strong></a></h5>
        <div class="small text-muted"><p>{{ new.date_creation|date:'d M Y' }}</div>
        <table>
            <tr>
                {% if new.image %}
                    <td class="leftcol">
                        <img src="{{ new.image.url }}" alt="img" class="fig">
                    </td>
                {% endif %}
                <td class="rightcol">
                    {{ new.post_text|truncatechars:450|censor }}<br><br>
                </td>
            </tr>
        </table>
    {% empty %}
        <li>Sorry, no news found in this category.</li>
    {% endfor %}

  {% include 'include/pagination.html' %}

{% endblock content %}

templates/news/search.html
{% extends 'main.html' %}
{% load my_filters %}
{% load i18n %}

{% block title %} News Search {% endblock title %}

{% block content %}
    <h2>{% trans "Последние публикации" %}</h2>

    <form method="get">
        <div>{{ filter.form }}
            <input type="submit" value="Поиск" class="btn btn-outline-secondary btn-sm" style="text-align: right"></div>
    </form>

    <a href="{% url 'news:subscribe' %}">{% trans 'Подписаться на рассылку' %} &raquo;</a>
    <hr>


    {% for new in filter.qs %}
        <h5><a href="{% url 'news:news_detail' new.url %}"><strong>{{ new.post_title|censor|safe }}</strong></a></h5>
        <div class="small text-muted"><p>{{ new.date_creation|date:'d M Y' }}</div>
        <table>
            <tr>
                {% if new.image %}
                    <td class="leftcol">
                        <img src="{{ new.image.url }}" alt="img" class="fig">
                    </td>
                {% endif %}
                <td class="rightcol">
                    {{ new.post_text|truncatechars:450|censor }}<br><br>
                </td>
            </tr>
        </table>
    {% empty %}
        <h5>По Вашему запросу статьи не найдены.</h5>
    {% endfor %}

   {% include 'include/pagination.html' %}

{% endblock content %}

templates/news/subscribe.html
{% extends 'main.html' %}

{% block content %}
    <hr>


<div style="margin-left: 30%">
<form action="" method="post" class="form-input">
    {% csrf_token %}
    <h3><label for="category_name">Выберите интересующие категории:<br></label></h3>
    {% for category in categories %}
        {% if category in cat_sub %}
            <h5><label for="category_name">
                <input type="checkbox" value="{{ category.category_name }}" name="category_name" checked>
            </label> {{ category.category_name }}</h5>
        {% else %}
            <h5><label for="category_name">
                <input type="checkbox" value="{{ category.category_name }}" name="category_name">
            </label> {{ category.category_name }}</h5>
        {% endif %}
    {% endfor %}
    <p class="small text-muted">Каждую неделю мы будем присылать Вам подборку статей из выбранных категорий.</p>
    <p class="placeholder-wave"><span><input type="submit" value="Сохранить" class="btn btn-outline-info"></span></p>
</form>
</div>

{% endblock content %}

templates/news/subscription_created.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
    <h3>Здравствуй, <strong>{{ user.username }}</strong>. </h3>
    <p>Новая статья в твоём любимом разделе {{ category.category_name }}!</p>
    <div class="container-sm">
        <h4>{{ post.post_title }}</h4>
        <p>{{ post.post_text|truncatechars:50 }} <a href="http://127.0.0.1:8000{{ post.get_absolute_url }}">читать на сайте</a></p>
    </div>
</body>
</html>

templates/news/weekly_subs_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h3>Здравствуй, <strong>{{ user.username }}</strong>. </h3>
    <h2>Свежие статьи за прошедшую неделю:</h2>
    <div class="container-sm">
        <ul style="list-style-type: none">
            {% for post in posts %}
                <li>{{ post.post_title }}<br>
                    {{ post.post_text|truncatechars:50 }}
                    <a href="http://127.0.0.1:8000{{ post.get_absolute_url }}">читать на сайте</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>