NewsPortal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from NewsPortal import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from NewsPortal import settings
from .views import *

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='news'),
    path('add-rating/', AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>', NewsDetail.as_view(), name='news_detail'),
    path('<slug:slug>/edit', NewsUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', NewsDelete.as_view(), name='delete'),
    path('search/', cache_page(60)(NewsSearch.as_view()), name='search'),
    path('add/', NewsCreate.as_view(), name='create'),
    path('upgrade/', upgrade_to_author, name='upgrade'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% extends 'main.html' %}
from django.contrib import admin

{% block title %}{% endblock title %}

{#{% block body %}#}
    {% block content %}

    {% endblock content %}
{#{% endblock body %}#}
{#{% block extra_body %}#}
{#{% endblock extra_body %}#}

templates/main.html
{% load static %}
{% load i18n %}
{% load recaptcha3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{% block title %}NewsPortal{% endblock title %}</title>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'news/css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'news/css/styles.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'news/assets/favicon.ico' %}"/>

    {% block css %} {% endblock css %}

    {% recaptcha_init %}
    {% recaptcha_ready action_name='homepage' %}
</head>
<body>
{% load cache %}

<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container" style="width: 55%">
        <a class="navbar-brand" href="/news">News Portal</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    {% if is_not_author %}
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:upgrade' %}">{% trans 'Стать автором' %}</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:create' %}">{% trans 'Добавить статью' %}</a></li>
                    {% endif %}
                {% endif %}

                <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:search' %}">{% trans 'Поиск' %}</a></li>

                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" aria-current="page" href="/accounts/logout/">{% trans 'Выйти' %}</a></li>
                    <li class="nav-item"><a class="nav-link" aria-current="page" style="text-decoration: none">| {{ user.username }}</a></li>

                {% else %}
                    <li class="nav-item"><a class="nav-link" aria-current="page" href="/accounts/login/">{% trans 'Войти' %}</a></li>
                {% endif %}
            </ul>

            <form action="{% url 'set_language' %}" method="post" style='font-family: -apple-system, BlinkMacSystemFont, "Segoe UI Light", wf_segoe-ui_light, Arial, "Helvetica Neue", Verdana, Helvetica, sans-serif;'>
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}">

                <select name="language" id="">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}

                    {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                            {{ language.code }}
                        </option>
                    {% endfor %}
                </select>
                <input type="submit" value="set" class="btn btn-outline-secondary btn-sm">
            </form>
        </div>
    </div>
</nav>

<div class="container" style="width: 55%">
    {% block content %}

    {% endblock content %}
    {% include 'include/footer.html' %}
</div>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>